### PR TITLE
Prep misc patches

### PR DESCRIPTION
**Pull request by jlebon**
(See individual commit messages.)

### CODE REVIEW

**Comment by lucab** [comment]
LGTM. For the network side, I double-checked https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/. I agree that we should drop the require, and we can queue ourselves after `network-online.target`. In practice this shouldn't matter, ignition is already aware that network setup may still be running at that time and thus it does multiple retries with backoff.

**Comment by dustymabe** [comment]
```
(Anyway, I think we want `network-online.target` here instead of
`network.target` but I haven't tested that).
```

yes. I believe from my reading the recommendation is that `network-online.target` is what people generally want when they specify `network.target`. I agree. I think when I was looking into this in the past `network-online.target` didn't exist for el7, so might be something we look at before we make a change.

**Comment by ajeddeloh** [comment]
I missed this going by, but I think this actually caused a regression. Now _nothing_ `Requires=network.target` and thus it's not getting pulled in at all. Why should we drop the require? Ignition requires networking.

**Comment by cgwalters** [comment]
> Ignition requires networking.

But not on qemu, which makes it *really* easy to make this kind of mistake.

(See also https://github.com/coreos/ignition-dracut/issues/94 )

**Comment by ajeddeloh** [comment]
Well on any platform it _can_ require networking, since you can fetch over the network, but yes, you can write configs that don't need it. That being said, I just did a build with the Requires= back in and it did not fix the problem.

**Pull request merged**
